### ISSUE TITLE
Devote more time to NumPy

### ISSUE THREAD

**Issue by btel** [swcarpentry/python-novice-gapminder#17]
I agree that pandas DataFrame is becoming the workforce of data analysis in Python. Recently, I gave as SC [lesson](https://github.com/btel/2015_eitn_swc_pandas) on pandas, which was received quite well. However, I think one should introduce or at least mention `numpy` in this lesson for several reasons:

- students leaving the course without basic familiarity of numpy will not be able to understand ~60% (my rough guess) of scientific Python applications (this is contradiciting the last goal listed for the lesson),
- much of pandas is based on numpy API
- pandas is big and complex and there are many ways to get yourself into trouble (for example, there are mutliple ways of indexing), numpy has a simpler design and uses only few concepts (indexing, ufuncs, dtype).

On the other hand:

- pandas includes (basic) plotting
- pandas can read and export to many data formats

**Comment by gvwilson** [comment]
NumPy got 20 minutes in an earlier version, but that had to be cut to 
meet our time budget.  What would you take out of the current plan to 
make room for re-introducing it?

**Comment by fonnesbeck** [comment]
It would be worth mentioning Numpy in the DataFrames section. This could be introduced in the context of transforming values within a column, prior to analyzing or plotting them (e.g. `df.apply(np.log)`). I would suggest this in place of the "normalize values" exercise in the last bullet point in this section.

This requires much less additional content than in previous modules because here NumPy is not being introduced as a foundational package providing the key data structure for the lessons, but rather as a "bag of functions" that can be applied to Pandas data structures.

**Comment by btel** [comment]
Personally I would remove "Debugging" and math library. I find that many beginners try to import the math library and apply the functions to lists or arrays, which doesn't give the expected output. I would replace math module with numpy ufuncs (sqrt etc.) and show how arrays can be used to "vectorise" operations.
