### ISSUE TITLE
Frequent, short exercises are pragmatically difficult

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/python-novice-gapminder#19]
The lesson includes many short 5-10 minute exercises. Is the intention to have the instructor working on these exercises interactively with the audience, or is there a dedicated break where the attendees work on the exercises themselves (or in small groups)? It has been my experience that the latter is quite difficult in practice. Novices need a lot of time to get oriented and understand the task they are being asked to perform.

Similarly, I've never managed to have a 15 minute coffee break. Attendees wander off or get deep into a conversation (this sort of discussion is valuable and I think worth encouraging). It usually ends up being 25-30 minutes long.

Overall, my point is that time estimates will always be underestimated compared to what happens in a live workshop where you have to manage a room full of people. A 6.5 hour lesson means that the last few topics will be rarely taught. One idea is to make sure the last [Wrap-Up](https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/index.md#wrap-up) lesson makes sense even if Programming Style and Debugging had to be skipped for time.

**Comment by gvwilson** [comment]
Each exercise section will include an MCQ and a fill-in-the-blanks 
exercise --- those are shorter (and the time more predictable).  But 
yes, we need a 5.5 hour plan to allow for all the over-time...

**Comment by fonnesbeck** [comment]
One of the advantages of using the Jupyter Notebooks is that they are explicitly hands-on, allowing learners to execute code as it is introduced by the instructor, and experiment with it as they go. This has led me to drop the use of shorter exercises in favor of one or two longer exercises per notebook.

**Comment by raynamharris** [comment]
I am a fan of multiple exercise. I wish I could get my colleagues at UT to incorporate them, but alas. 

I think it would be nice to make a Socrative question bank for all the short exercise questions so that the instructor can administer them and get realtime feedback on learner responses. I think it can help keep the time devoted to each question very manageable. Also, this gives the added benefit of collecting data on what students are learning and which questions/exercise instructors chose to administer.
