### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/python-novice-gapminder#230]
Is there a reason that the data files are all in a "wide" format as opposed to "tall"? My past experience with this dataset would have had the columns: 
| country | continent | year | gdp | life expectancy
And more rows of data rather than the 
| country | continent | gdp_year | gdp_year | gdp_year | etc | lifexpect_year | lifexpect_year | etc | 
That's currently in the lesson.  

The current format (sort of) takes away the need for group_by by grouping years naturally by columns instead of choosing to aggregate them by row values.  However, the tidy data movement (which I think applies across R and Python) doesn't typically organize data this way.  

Thoughts?  Forgive me if this is a recurrent issue - I haven't taught this lesson yet so am only now looking at it carefully.

**Comment by ntmoore** [comment]
My impression is that the rows vs columns representation is just an artifact of how spreadsheets are arranged.  I haven't done anything different because of momentum - no other reason.

**Comment by ChristinaLK** [comment]
Okay, cool.  I'm going to teach this in 3 weeks and if I do something different (and it goes well) will submit a PR.  :)

**Comment by ntmoore** [comment]
That would be great!

**Comment by Ageotas** [comment]
After teaching this a couple of weeks ago, I can see both arguments; I think the problem lies in used the Oceana subset of the gapminder data.

Because Oceana only has two "observations" (Australia and New Zealand), it doesn't make sense for it to be presented wide, but as soon as you look at the full dataset it makes far more sense.

I think the solution to this problem is not getting students to start by loading in pre-subsetted csv files, but rather pull the full gapminder set so they understand the context of the data (and appreciate Pandas ability to subset easily!)

**Comment by ChristinaLK** [comment]
@Ageotas I agree.  I think there are some substantial changes I would make to this lesson but haven't had the bandwidth to help organize.  I'm hoping that'll happen in the new year...

**Comment by martinosorb** [comment]
Closing this old issue as there was general agreement that this was a problem noticeable in the Oceania file only. There does not seem much else to discuss on the topic.
