### ISSUE TITLE
Pandas lessons - Using pandas alias

### ISSUE THREAD

**Issue by cschlosberg** [swcarpentry/python-novice-gapminder#382]
In the Pandas DataFrames and Reading Tabular Data into DataFrames lessons, I think pandas should be imported as an alias:
```import pandas as pd``` instead of ```import pandas```. Then each of the function can be used aliased: ```data = pd.read_csv('data/gapminder_gdp_oceania.csv')``` instead of ```data = pandas.read_csv('data/gapminder_gdp_oceania.csv')```. I find this to be very common practice and is supported in the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html). In addition, it can be create consistency across lessons. For example, in the Plotting lesson, matplotlib is imported as an alias: `import matplotlib.pyplot as plt`.

**Comment by alee** [comment]
I agree, this would be a good change for consistency since it is pretty established convention (across official documentation, examples, and existing code) to `import pandas as pd` and `import numpy as np`

**Comment by rantahar** [comment]
I added pull requests for the change. I think it's a good idea to mention this pattern, since it is common in examples and discussion, as @cschlosberg says, and often goes unexplained. This will also reinforce aliasing, which is introduced in the lesson 5.

I'm not sure if the alias should be used in the text, as opposed to code blocks. I chose to change any references to pandas.function to pd.function also in the text for consistency.
