### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/python-novice-gapminder#393]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll make a first pass and add issues that are already marked "help-wanted", but please feel free to update the milestone at your convenience. Please let me know if you have any questions!

**Comment by souravsingh** [comment]
Yes, we are in

**Comment by ErinBecker** [comment]
Great, thanks @souravsingh!

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by alee** [comment]
There's one FIXME in the afternoon coffee interlude where we should add some initial placeholders or text: 

http://swcarpentry.github.io/python-novice-gapminder/16-coffee/index.html

At this point the new material covered since lunch would have been sequences and iteration, some file processing in episode 13, functions and variable scope. As a first cut how about something like:

- a common refrain in software engineering is "Don't Repeat Yourself" - how do the tools we've learned in the last few lessons help us avoid repeating ourselves? *note that in practice there is a lot of nuance here and it should be balanced with doing the simplest thing that could possibly work*
- How do you decide whether to make a variable global or local to a function? What are the drawbacks or benefits of your decisions?
- How do you decide when to convert a block of code into a function definition?

**Comment by alee** [comment]
```
% linkchecker http://swcarpentry.github.io/python-novice-gapminder/                                                                                              [13:24:50]
INFO 2019-06-05 13:24:51,254 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2019-06-05 13:24:51-007
10 threads active,    70 links queued,   20 links in   3 URLs checked, runtime 1 seconds
10 threads active,    54 links queued,   36 links in  19 URLs checked, runtime 6 seconds
10 threads active,   413 links queued,  587 links in  31 URLs checked, runtime 11 seconds
10 threads active,   637 links queued, 1431 links in  45 URLs checked, runtime 16 seconds
10 threads active,   580 links queued, 1919 links in  56 URLs checked, runtime 21 seconds
10 threads active,   347 links queued, 2241 links in  64 URLs checked, runtime 26 seconds
10 threads active,   112 links queued, 2560 links in  80 URLs checked, runtime 31 seconds
10 threads active,    58 links queued, 3571 links in  92 URLs checked, runtime 36 seconds
 1 thread active,     0 links queued, 4590 links in  99 URLs checked, runtime 41 seconds

Statistics:
Downloaded: 1.79MB.
Content types: 908 image, 2722 text, 0 video, 0 audio, 190 application, 62 mail and 780 other.
URL lengths: min=17, max=126, avg=72.

That's it. 4662 links in 99 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2019-06-05 13:25:32-007 (41 seconds)
```

**Comment by alee** [comment]
For the "file structure is clean" portion, there are a few empty directories with a .gitkeep in them that may not be necessary:

```
- _episodes_rmd/
- code/
```

these seem fairly minor though so I'm ok with checking that one off.

**Comment by ErinBecker** [comment]
Awesome work @swcarpentry/python-novice-gapminder-maintainers and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3264983
