### ISSUE TITLE
Use of conditionals before teaching it

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/python-novice-gapminder#462]
In 14-writing-functions the exercises "Find the First" and "Encapsulate of If/Print Block" use conditional statements, but these are not taught until 17-conditionals. This exercise can be moved there, but makes less sense as it aims to practice turning code into a function.

**Comment by lexnederbragt** [comment]
There is actually another conditional in that lesson, the `def average(values):` example.

**Comment by alee** [comment]
Thanks for the report! What do you think about placing conditionals before functions? On a cursory glance we would only need to replace / move the "Using Functions With Conditionals in Pandas" exercise to the Writing Functions episode then. And coding style might be a good followup to encapsulation via functions.

**Comment by lexnederbragt** [comment]
I think that would be a great solution!

**Comment by wood-chris** [comment]
I came here to report exactly this issue...! I'm glad someone else spotted it :)

**Comment by alee** [comment]
We'd need to keep the Scope episode following the Functions, so a possible new episode order would be:

14-conditionals
15-beverage break
16-writing functions
17-scope
18-programming style

thoughts from other @swcarpentry/python-novice-gapminder-maintainers ?

**Comment by drewhart** [comment]
I agree with this suggestion! 

Not only for the reasons mentioned above, but also for an additional reason: The stated goal of the lesson is to provide an intro to Python, motivated by plotting. And for many attendees this may be their first introduction to programming in general. For this reason, it would be a shame to go through the lessons in order, run out of time, and wind up not covering conditionals, which are a crucial, basic component of programming. The further down the "Conditionals" section is moved, the higher the risk of this. If even for this reason only, I would advocate for moving it earlier.

In fact, I might even suggest moving "Conditionals" to before "Looping over Data Sets", for two reasons:
    1. "Conditionals" strikes me as a natural follow-on to "For Loops".
    2. Once conditionals have been introduced, then the "glob" section of "Looping over Data Sets" could be replaced with an `if filename.endswith('csv'):` statement. Glob is nice, but it seems like it could be unnecessary cognitive overload. It could perhaps be introduced in an activity at the bottom instead, as an alternative to the conditional approach. But using a conditional statement instead would provide a nice, context-relevant example of the utility of conditionals, without requiring more new content.

So that would be a suggested order of:

12 - for loops
13 - conditionals
14- looping over data sets
15-beverage break
16-writing functions
17-scope
18-programming style


Just brainstorming! Curious to hear if others agree or disagree.

**Comment by amasson84** [comment]
I did a PR for this modification :
https://github.com/swcarpentry/python-novice-gapminder/pull/471
