### ISSUE TITLE
Dock Panel instead of Work Area?

### ISSUE THREAD

**Issue by nicoguaro** [swcarpentry/python-novice-gapminder#480]
In the lesson [Running and Quitting](https://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html) the term "dock panel" is used in the section **Menu Bar**:

> **Tabs:** A list of the open documents and activities in the dock panel.

This term is not used in any other part of the document and I think that it refers to "Work Area", that is used several times in the lesson.

**Comment by vahtras** [comment]
The jupyter lab documentation uses the term "Main Work Area", https://jupyterlab.readthedocs.io/en/stable/user/interface.html#main-area, so I support your suggestion, in particular if dock panel is not used or explained  anywhere else. Please submit a PR

**Comment by nicoguaro** [comment]
I have done thad in PR #481.

**Comment by alee** [comment]
Thanks for pointing this out and the PR! I think this terminology was pulled directly from here: 

https://jupyterlab.readthedocs.io/en/stable/user/interface.html#menu-bar

But I agree it seems confusing since it's the list of open documents and activities in the main work area (and listed in the dock panel which I assume to be the tabset in the main work area). I'm fine with replacing it with main work area as well.
