### ISSUE TITLE
matplotlib not found to be imported

### ISSUE THREAD

**Issue by afalomir** [swcarpentry/python-novice-gapminder#494]
In episode 9 Plotting, `matplotlib` library can´t be imported. 

It seems Anaconda 1.9.12 (conda 4.8.2) for Windows is lacking this library.

In the initial Setup it could be added a step to download it using Anaconda Prompt:

`conda install -c anaconda matplotlib`

**Comment by eldobbins** [comment]
I recently installed Anaconda 1.10.0 on a Windows PC, and the Matplotlib library was included in the base installation  - along with numpy and pandas and many others.

Perhaps this change is no longer needed.  However, if it is needed, I can submit a PR.  But I'm unsure if the remedy suggested is the right one because it opens a Conda can of worms.  Would upgrading Anaconda add those libraries too?

**Comment by alee** [comment]
thanks for the updated report @eldobbins ! I'm also unable to reproduce and it appears that all recent versions of anaconda include matplotlib (https://docs.anaconda.com/anaconda/packages/pkg-docs/)

Please reopen if this issue is still relevant.. thanks!
