### ISSUE TITLE
Adding use of GitHub or Git Lab in the Prerequisites 

### ISSUE THREAD

**Issue by espirado** [swcarpentry/python-novice-gapminder#557]
One thing i have learnt of the years in my programming learning journey is using of GitHub to keep track of my learning has played a major role not just on a personal level but also creating a visibility to others on my skills. A certificate is a mere representation of ones effort which might not fully reflect what the learner has learned or is capable of but using git lab or GitHub can go a step in showing every single step of the learners journey in relation to the various aspects in the lesson.

**Comment by martinosorb** [comment]
Hi @espirado, I'm going through some old issues. Thank you for your comment. As part of software carpentry workshops, we usually also deliver lessons on git and github, but these are not part of this repository, which is for introductory python.

I'm closing this now due to lack of activity and concrete suggestions, but happy to reopen if I've misunderstood your comment.
