### ISSUE TITLE
Take out testing

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/python-novice-gapminder#6]
If there is a need to save time, Testing could go - unfortunate, but it deserves a separate lesson. It could be mentioned during the Defensive Programming part.

**Comment by gvwilson** [comment]
Agreed.

**Comment by IanHawke** [comment]
I was just going to raise an issue to go the other way: replace Defensive Programming with testing. Time constraints may force it to go this way, but I'm moving towards testing being more important as a way of thinking that DP.

**Comment by lexnederbragt** [comment]
I agree in principle, but am not sure whether it is practically achievable for this lesson. I would think - admittedly without any real practical experience - that adding assertions to functions is fairly quickly done, while writing separate testing functions and getting Nose (or another such library) to work adds quite some time (and cognitive load). How about something that tries to discuss both, but goes through only one of them - where I would suggest DP?

**Comment by IanHawke** [comment]
My argument for simplicity is more about how to talk about motivating it and extending it. I'd still do testing by adding an assert to a function (although now it's the testing function, not the original), where it tests output on simple input. Just that test function can then be run. Testing frameworks like nose can be mentioned, particularly in conjunction with CI, as "how to extend to fully automated". But conceptually, each new test is separate, and forms a separate function.

With DP, my concern is that any sufficiently "real" example leads to assertion code that overwhelms the real code in the function. Whilst the typical SWC/GVW anecdata states that this is true for production code, it does undermine the "program for humans, and for novices" aims, and I think puts people off doing it until too late.

**Comment by wking** [comment]
On Mon, Feb 08, 2016 at 01:28:15AM -0800, Ian Hawke wrote:
> With DP, my concern is that any sufficiently "real" example leads to
> assertion code that overwhelms the real code in the function.

Which is why languages like Python that bubble exceptions are so nice
:).  You only need code to catch/handle exceptions that you want to
catch/handle, and you can punt most validation to the lowest-level
functions that can apply those assertions.

> Whilst the typical SWC/GVW anecdata states that this is true for
> production code, it does undermine the "program for humans, and for
> novices" aims…

In many cases, novice programmers can rely on the libraries the call
to perform these error checks.  For example, if you divide by zero,
Python will raise ZeroDivisionError for you, so there's no need to
check up front if the divisor is zero.  If you try to open a URL with
an unrecognized scheme, urllib.request.urlopen will raise a URLError.

So while it's important to mention that pretty much everything can
fail under the right (wrong?) conditions, you don't actually need that
many explicit checks to ensure your function doesn't silently ignore
errors.  The assertions in [1] seem fairly arbitrary (why not use
‘abs(x1 - x0)’ instead of requiring x1 > x0?), but with the focus on
Gapminder data there may be more realistic checks we can use for
modeling.

On the other hand, testing or defensive programming is clearly
secondary to being able to write functions, do flow control, etc.,
because without them you'll have nothing to test ;).  So if something
needs to get punted, testing has been our traditional choice.

> But conceptually, each new test is separate, and forms a separate
> function.

That's good unit testing, but having defensive checks at some point in
the working call stack is still useful.  Testing is about “when I give
this known-good (or known-bad) data, the function successfully
generates this known-good result (or raises the appropriate
exception)”.  That lets you automatically check that the software does
what you expect.

Defensive programming, on the other hand, is the implementation of
“raising the appropriate exception”, just like the rest of the code is
the implementation of “returning the right result for good input”.

[1]: https://github.com/swcarpentry/bc/blob/gh-pages/novice/python/05-defensive.md

**Comment by IanHawke** [comment]
I should say that in my experience of teaching/using Matlab, DP is pretty much the same as in Python, but unit testing is much more work. It may be that, as I'm moving more towards Python and away from Matlab, I'm seeing unit testing as the "new shiny" in comparison to DP.

**Comment by wking** [comment]
On Mon, Feb 08, 2016 at 01:41:05PM -0800, Ian Hawke wrote:
> … I'm seeing unit testing as the "new shiny" in comparison to DP.

I think we have conflated unit testing and defensive programming in
the past as two ways of getting at the same thing.  I think it's worth
distinguishing between the two, and I tried to make that distinction
towards the end of [1].  “Automatically driving the software to ensure
good behavior” (i.e. test suites) and “raising an appropriate error
when things go wrong” (i.e. defensive programming) aren't the same
thing, and the latter (DP) will be part of the former (testing).

[1]: https://github.com/swcarpentry/python-novice-gapminder/issues/6#issuecomment-181517471

**Comment by wking** [comment]
On Wed, Mar 23, 2016 at 07:02:46AM -0700, Greg Wilson wrote:
> Closed #6.

What was the resolution here?  It looks like we still have defensive
programming [1,2] and something that sounds like unit testing [3].
But maybe [3] is stale?  And there's a big “Is This Needed?” caveat in
[2].

Looking through the history with ‘git log -p -G test’, it looks like
80c7e77d (Committing to Pandas, 2016-01-23) dropped the explicit
“Testing” section and its Nose reference [4].  That has the right
timing to be the source of the initial close [5], but I'm not sure how
the comment triggering the re-open [6] was addressed.

[1]: https://github.com/swcarpentry/python-novice-gapminder/blame/f52b1887f961150e3771f73923db42bf734b263f/design.md#L296
[2]: https://github.com/swcarpentry/python-novice-gapminder/blob/f52b1887f961150e3771f73923db42bf734b263f/19-defensive.md
[3]: https://github.com/swcarpentry/python-novice-gapminder/blame/f52b1887f961150e3771f73923db42bf734b263f/design.md#L152
[4]: https://github.com/swcarpentry/python-novice-gapminder/commit/80c7e77d3645ab9f086785240103d05eaf14d403#diff-d680e8a854a7cbad6d490c445cba2ebaL216
[5]: https://github.com/swcarpentry/python-novice-gapminder/issues/6#event-524250760
[6]: https://github.com/swcarpentry/python-novice-gapminder/issues/6#issuecomment-180367701
